spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: test-client-id
            client-secret: test-client-secret
            redirect-uri: http://localhost:8080/index
            client-authentication-method: POST
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


url:
  base: http://localhost:8080/auth/kakao/callback