name: Code Coverage sample

on:
  push:
    branches:
      - 'workflow'
  pull_request:
    branches:
      - 'workflow'

jobs:
  code-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Make /tmp directory
        run: mkdir -p /tmp
          chmod 755 /tmp


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew build


      - name: Report to CodeCov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          slug: oob00/Wakuwaku